#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-new"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "db74ae9ef54d49dba47bd39176f0576b" }
]

[assets]
directory = "./public"
